apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-gc
  namespace: kubeflow-user-example-com
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-gc
  namespace: kubeflow-user-example-com
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get","list","delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-gc
  namespace: kubeflow-user-example-com
subjects:
- kind: ServiceAccount
  name: pod-gc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-gc
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: kfp-pod-gc
  namespace: kubeflow-user-example-com
spec:
  schedule: "0 */12 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: pod-gc
          restartPolicy: Never
          containers:
          - name: gc
            image: bitnami/kubectl:1.33.4-debian-12-r0
            imagePullPolicy: Always
            command: ["sh","-c"]
            args:
            - |
              set -e
              NS="$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)"
              RETAIN_SECS=$((12*3600))
              now=$(date +%s)
              kubectl -n "$NS" get pods -l 'pipelines.kubeflow.org/v2_component' \
                -o jsonpath='{range .items[*]}{.metadata.name}{"|"}{.status.phase}{"|"}{.status.startTime}{"\n"}{end}' \
              | while IFS='|' read -r name phase start; do
                  [ "$phase" = "Succeeded" ] || [ "$phase" = "Failed" ] || continue
                  [ -n "$start" ] || continue
                  start_epoch=$(date -d "$start" +%s)
                  age=$((now - start_epoch))
                  if [ $age -gt $RETAIN_SECS ]; then
                    echo "deleting $name (age=${age}s, phase=$phase)"
                    kubectl -n "$NS" delete pod "$name"
                  fi
                done
